# Site settings
author:  Alice
title: Blog Title
header-img: img/home-bg.png
email: agenkin1@gmail.com
copyright_name:  Alice
description: > # this means to ignore newlines until "baseurl:"
  Blog Subtitle
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alicegenkin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
